name: build docs (to test changes in PRs)
on: [push, pull_request]
permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install required Python packages
        run: |
            pip install -r requirements.txt
            cd custom_plugin && pip install . && cd -
            cd computational_macros && pip install . && cd -
            python3 -m pip list
            mkdocs --version

      # equivalent of 'mkdocs build', but need to build all flavors of the docs (different site/OS)
      - name: build docs
        run: |
          python3 build.py
          find build -type f

  # Add a job to check links after the docs have been built
  link-check:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check links
        run: |
          grep -rHoP "$a_tag_regex" build | sed 's/:<a.*href="/ /' | sort -k2,2 | uniq -f1
