name: HTML tag detection

on: [push, pull_request]  # Trigger on push or pull request events

jobs:
  link-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run grep command
        run: |
          grep -Ho '</[^>]*>' mkdocs/docs/HPC/*.md
